name: Publish

on:
    push:
        branches: main

jobs:
    build:
        name: Build & publish
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Install pipx
              run: python -m pip install pipx

            - name: Install poetry
              run: pipx install poetry

            - name: Install dependencies
              run: poetry install

            - name: Build and publish to PyPI
              uses: JRubics/poetry-publish@v2.0
              with:
                  pypi_token: ${{ secrets.PYPI_TOKEN }}
