name: Publish

on:
    workflow_run:
        workflows: ["Test"]
        branches: [main]
        types:
            - completed

jobs:
    check-pyproject-change:
        runs-on: ubuntu-latest
        outputs:
            changed: ${{ steps.filter.outputs.changes }}
        steps:
            - uses: actions/checkout@v4
            - name: Check for pyproject.toml changes
              id: filter
              uses: dorny/paths-filter@v2
              with:
                  filters: |
                      pyproject:
                        - 'pyproject.toml'
    publish:
        needs: check-pyproject-change
        if: needs.check-pyproject-change.outputs.changed == 'true'
        name: Build & publish
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.11

            - name: Install poetry
              run: pipx install poetry

            - name: Install dependencies
              run: poetry install

            - name: Build and publish to PyPI
              uses: JRubics/poetry-publish@v2.0
              with:
                  pypi_token: ${{ secrets.PYPI_TOKEN }}
